name: "Chromatic"
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v1
        # see https://github.com/actions/cache/blob/master/examples.md#node---npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/checkout@v1
      - run: |
          npm i
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.chromatic }}
          token: ${{ secrets.GITHUB_TOKEN }}
