name: "Chromatic"
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          npm i
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.chromatic }}
          token: ${{ secrets.GITHUB_TOKEN }}
